### ISSUE TITLE
IDEA 启动时有插件的报错信息

### ISSUE THREAD

**Issue by f1ynnzhan9** [alibaba-cloud-toolkit/cloud-toolkit-jetbrains#3]
**Bug描述**
IDEA 启动时有插件的报错信息，请参见截图。

**复现路径**
无

**期望的行为**
IDEA 启动时没有插件的报错信息。

**截图**
![image](https://user-images.githubusercontent.com/80672942/123894546-f0004680-d990-11eb-9c64-3af77cbd217f.png)

**运行环境**
- 操作系统: Windows 10 专业工作站版 20H2 19042.1081
- JetBrains 产品类型: Ultimate Edition
- JetBrains 产品版本: IntelliJ IDEA 2021.1.2
- Cloud Toolkit 版本: 2021.4.1

**附加上下文**
无

**Comment by anjia0532** [comment]
同样的问题

Cloud Toolkit 版本: 2021.4.1
JetBrains 产品版本: IntelliJ IDEA 2021.1.3

```
java.lang.RuntimeException: Invalid version number: ; plugin name: null
	at com.intellij.openapi.util.BuildNumber.parseBuildNumber(BuildNumber.java:179)
	at com.intellij.openapi.util.BuildNumber.fromString(BuildNumber.java:159)
	at com.intellij.ide.plugins.PluginManagerCore.checkBuildNumberCompatibility(PluginManagerCore.java:994)
	at com.intellij.ide.plugins.PluginManagerCore.checkBuildNumberCompatibility(PluginManagerCore.java:977)
	at com.intellij.ide.plugins.PluginManagerCore.isIncompatible(PluginManagerCore.java:971)
	at com.intellij.ide.plugins.PluginManagerCore.isIncompatible(PluginManagerCore.java:964)
	at com.intellij.ide.plugins.PluginManagerCore.isCompatible(PluginManagerCore.java:956)
	at com.intellij.ide.plugins.InstalledPluginsState.onDescriptorDownload(InstalledPluginsState.java:118)
	at com.intellij.openapi.updateSettings.impl.UpdateChecker.buildDownloaderAndPrepareToInstall(UpdateChecker.kt:425)
	at com.intellij.openapi.updateSettings.impl.UpdateChecker.validateCompatibleUpdatesForCurrentPlugins(UpdateChecker.kt:409)
	at com.intellij.openapi.updateSettings.impl.UpdateChecker.checkPluginsUpdate(UpdateChecker.kt:304)
	at com.intellij.openapi.updateSettings.impl.UpdateChecker.checkPluginsUpdate$default(UpdateChecker.kt:282)
	at com.intellij.openapi.updateSettings.impl.UpdateChecker.getPluginUpdates(UpdateChecker.kt:139)
	at com.alibabacloud.intellij.util.PluginUtils.checkUpdateAndReturnDownloader(PluginUtils.java:81)
	at com.alibabacloud.intellij.core.ToolkitProject.lambda$projectOpened$0(ToolkitProject.java:40)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
![image](https://user-images.githubusercontent.com/15098916/123911734-bcccb000-d9ae-11eb-9a6c-6d602283e661.png)

**Comment by KaihangXing** [comment]
收到，这个异常是在检查插件版本更新时遇到的，已在下一个版本中修复，感谢反馈
